---
name: Lint Python

on:
  pull_request:
    paths:
      - "**.py"
  push:
    paths:
      - "**.py"

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    name: flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      # Install flake8 extensions (this step is not required. Default is "None").
      - run: pip install flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          fail_level: error
