---
name: Lint Shell Scripts

on:
  pull_request:
    paths:
      - "**.sh"
  push:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: shellcheck
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      # Install flake8 extensions (this step is not required. Default is "None").
      - run: pip install flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes
      - name: flake8 Lint
        uses: reviewdog/action-shellcheck@v1
        with:
          fail_level: error
