name: flake8

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ "github-pr-check" if github.event.type == "pull_request" else "github-check" }}
